services:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      TZ: Europe/Stockholm
    ports:
      - "${PORT}:80"
    volumes:
      - ./www/public:/var/www/public:ro,z
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro,z
    depends_on:
      - php
    networks:
      - app-network

  php:
    build: ./docker/php
    image: lemp-php:dev
    container_name: php
    restart: unless-stopped
    command: php-fpm
    volumes:
      - ./www:/var/www:z
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:ro,z
    environment:
      TZ: Europe/Stockholm
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql:z
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf:ro,z
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD:-12345}
      TZ: Europe/Stockholm
    networks:
      - app-network

  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma
    restart: unless-stopped
    volumes:
      - ./config/pma/config.inc.php:/etc/phpmyadmin/config.inc.php
    environment:
      PMA_HOST: mariadb
      TZ: Europe/Stockholm
    depends_on:
      - mariadb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge